
// Mock courses data
export const getAllCourses = () => [
  {
    id: 1,
    title: "Java Fundamentals",
    description: "Learn the basics of Java programming language, including syntax, data types, and object-oriented programming concepts.",
    level: "Beginner",
    category: "Java",
    modules: 12,
    duration: "20 hours",
    students: 1245,
  },
  {
    id: 2,
    title: "Python for Beginners",
    description: "Start your Python journey with this comprehensive course covering Python basics, data structures, and control flow.",
    level: "Beginner",
    category: "Python",
    modules: 10,
    duration: "15 hours",
    students: 2350,
  },
  {
    id: 3,
    title: "JavaScript Essentials",
    description: "Master the fundamentals of JavaScript, from basic syntax to DOM manipulation and asynchronous programming.",
    level: "Beginner",
    category: "JavaScript",
    modules: 8,
    duration: "12 hours",
    students: 1870,
  },
  {
    id: 4,
    title: "Advanced Java Programming",
    description: "Dive deep into Java with advanced topics like concurrency, streams, lambdas, and design patterns.",
    level: "Intermediate",
    category: "Java",
    modules: 15,
    duration: "25 hours",
    students: 875,
  },
  {
    id: 5,
    title: "Python Data Analysis",
    description: "Learn how to analyze data using Python libraries like Pandas, NumPy, and Matplotlib.",
    level: "Intermediate",
    category: "Python",
    modules: 14,
    duration: "22 hours",
    students: 1430,
  },
  {
    id: 6,
    title: "Full-Stack JavaScript",
    description: "Build complete web applications with JavaScript, Node.js, Express, and React.",
    level: "Intermediate",
    category: "JavaScript",
    modules: 18,
    duration: "30 hours",
    students: 1120,
  },
];
